;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        emmet-expand-line
        indent-for-tab-command
        org-cycle
        org-self-insert-command
        web-mode-buffer-indent
        ))

(setq mc/cmds-to-run-once
      '(
        ))
